apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # {kind_plural}.{group} where
  # kind_plural: myresources
  # group: mygroup.com
  name: myresources.mygroup.com
spec:
  group: mygroup.com # group
  names:
    kind: MyResource
    listKind: MyResourceList
    plural: myresources
    singular: myresource
    shortNames:
      - myres
  # scope
  # Namespaced: allowing multiple instances with the same name across different namespaces.
  # Cluster: each instance is unique across the whole cluster.
  scope: Namespaced
  versions:
    - name: v1
      served: true  # whether avail for client to interact
      storage: true # whether persisted to etcd, only one version could be true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              # ++ constraint
              required: [ "msg" ]
              properties:
                msg:
                  type: string
                  # ++ constraint
                  maxLength: 15
      additionalPrinterColumns: # for kubectl get
        - name: age
          jsonPath: .metadata.creationTimestamp
          type: date
        - name: message
          jsonPath: .spec.msg
          type: string